quarkus:
  application:
    name: RandomThoughts
  http:
    port: ${API_PORT}
  log:
    level: "INFO"
    console:
      enable: true
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PWD}
    jdbc:
      url: jdbc:postgresql://${DB_HOST}/${DB_SCHEMA}
  hibernate-orm:
    database:
      generation: 
        ~: update
